services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/lib/jelastic/keys:/var/lib/jelastic/keys:ro 

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - DJANGO_SETTINGS_MODULE=kaep.settings
      - DATABASE_URL=sqlite:///db.sqlite3