services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    expose:
      - "3000"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - DJANGO_SETTINGS_MODULE=kaep.settings
      - DATABASE_URL=sqlite:///db.sqlite3

# services:
#   frontend:
#     build:
#       context: ./frontend
#     ports:
#       - "3000:80"
#     depends_on:
#       - backend
#     networks:
#       - app-network

#   backend:
#     build:
#       context: ./backend
#     ports:
#       - "8000:8000"
#     environment:
#       - DJANGO_SETTINGS_MODULE=kaep.settings
#       - DATABASE_URL=sqlite:///db.sqlite3
#     volumes:
#       - ./backend:/app
#     networks:
#       - app-network

#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#     depends_on:
#       - frontend
#       - backend
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge
