version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - frontend
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DATABASE_URL=sqlite:///db.sqlite3
