# Generated by Django 5.1 on 2024-08-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_event_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_kz',
            new_name='title_kk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
